snoop:
   applicationName: snoopydemo
   applicationHome: http://localhost:8080/snoopy-demo/
   serviceUrl: ws://localhost:8080/snoop-service/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  